# Generated by Django 4.2.3 on 2023-11-01 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_topicgroup_is_public_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='moderate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
