# Generated by Django 4.2.3 on 2023-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_topic_moderate'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgroup',
            name='group_sid',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
