# Generated by Django 4.2.3 on 2023-08-07 07:48

from django.db import migrations
from chat.models import Topic

topic_data = ['Politics', 'Music', 'Gaming', 'News', 'College', 'Movies', 'Motorcycles', 'Programming', 'History']

def create_defaults_topic(apps, schema_editior):
    for i in topic_data:
        Topic.objects.get_or_create(name=i)
        print("Topic data added sucessfully")



class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_topicgroup_group_sid'),
    ]

    operations = [
        migrations.RunPython(create_defaults_topic,)
    ]
